From python:3.10-slim

WORKDIR /app

COPY server.py util.py .
COPY artifacts/ ./artifacts/

RUN pip install fastapi uvicorn numpy==1.26.4 pandas scikit-learn==1.2.2 python-multipart

EXPOSE 8000

CMD ["uvicorn","server:app","--host","0.0.0.0","--port","8000"]